export const defaultClassicFeature = {
  slug: "court-classic",
  image: "",
  imageAlt: "",
  watermark: "CLASSIC",
  badge: "Legacy Essential",
  styleLabel: "Style",
  styleValue: "Court / 01",
  caption: "The Everyday Pair",
  name: "",
  color: "",
  eyebrow: "Timeless For A Reason",
  heading: "The pair that",
  accent: "always works.",
  description: "",
  colorLabel: "Colourway",
  priceLabel: "Price",
  button: "",
  href: "#collection",
};
export type ClassicFeatureSettings = typeof defaultClassicFeature;
