-- Generated catalogue additions. Suggested prices; stock starts at zero until verified.
-- Requires the product variants migration. Re-running never overwrites existing products.
begin;
insert into public.categories(name) values ('Everyday'), ('Runners') on conflict (name) do nothing;
insert into public.products(slug,name,category,color,price,image,tag,description,details,stock,size_stock,gallery,size_guide,featured) values
('dune-runner', 'Dune Runner', 'Runners', 'Sand / Cream', 6490, '/images/shoes/dune-runner.png', 'New arrival', 'Dune Runner brings sand / cream tones to your everyday rotation. A versatile silhouette made to pair with your favourite casual looks.', '["Lace-up silhouette","See size guide before ordering","Colour may vary slightly by screen"]'::jsonb, 0, '{"UK 6":0,"UK 7":0,"UK 8":0,"UK 9":0,"UK 10":0}'::jsonb, '["/images/shoes/dune-runner.png"]'::jsonb, '[{"size":"UK 6","footLength":"25 cm"},{"size":"UK 7","footLength":"26 cm"},{"size":"UK 8","footLength":"27 cm"},{"size":"UK 9","footLength":"28 cm"},{"size":"UK 10","footLength":"29 cm"}]'::jsonb, false),
('forest-runner', 'Forest Runner', 'Runners', 'Forest / Ivory', 6790, '/images/shoes/forest-runner.png', 'New arrival', 'Forest Runner brings forest / ivory tones to your everyday rotation. A versatile silhouette made to pair with your favourite casual looks.', '["Lace-up silhouette","See size guide before ordering","Colour may vary slightly by screen"]'::jsonb, 0, '{"UK 6":0,"UK 7":0,"UK 8":0,"UK 9":0,"UK 10":0}'::jsonb, '["/images/shoes/forest-runner.png"]'::jsonb, '[{"size":"UK 6","footLength":"25 cm"},{"size":"UK 7","footLength":"26 cm"},{"size":"UK 8","footLength":"27 cm"},{"size":"UK 9","footLength":"28 cm"},{"size":"UK 10","footLength":"29 cm"}]'::jsonb, false),
('slate-runner', 'Slate Runner', 'Runners', 'Slate / Silver', 6990, '/images/shoes/slate-runner.png', 'New arrival', 'Slate Runner brings slate / silver tones to your everyday rotation. A versatile silhouette made to pair with your favourite casual looks.', '["Lace-up silhouette","See size guide before ordering","Colour may vary slightly by screen"]'::jsonb, 0, '{"UK 6":0,"UK 7":0,"UK 8":0,"UK 9":0,"UK 10":0}'::jsonb, '["/images/shoes/slate-runner.png"]'::jsonb, '[{"size":"UK 6","footLength":"25 cm"},{"size":"UK 7","footLength":"26 cm"},{"size":"UK 8","footLength":"27 cm"},{"size":"UK 9","footLength":"28 cm"},{"size":"UK 10","footLength":"29 cm"}]'::jsonb, false),
('cloud-court', 'Cloud Court', 'Everyday', 'White / Cream', 5990, '/images/shoes/cloud-court.png', 'New arrival', 'Cloud Court brings white / cream tones to your everyday rotation. A versatile silhouette made to pair with your favourite casual looks.', '["Lace-up silhouette","See size guide before ordering","Colour may vary slightly by screen"]'::jsonb, 0, '{"UK 6":0,"UK 7":0,"UK 8":0,"UK 9":0,"UK 10":0}'::jsonb, '["/images/shoes/cloud-court.png"]'::jsonb, '[{"size":"UK 6","footLength":"25 cm"},{"size":"UK 7","footLength":"26 cm"},{"size":"UK 8","footLength":"27 cm"},{"size":"UK 9","footLength":"28 cm"},{"size":"UK 10","footLength":"29 cm"}]'::jsonb, false),
('espresso-court', 'Espresso Court', 'Everyday', 'Brown / Gum', 6290, '/images/shoes/espresso-court.png', 'New arrival', 'Espresso Court brings brown / gum tones to your everyday rotation. A versatile silhouette made to pair with your favourite casual looks.', '["Lace-up silhouette","See size guide before ordering","Colour may vary slightly by screen"]'::jsonb, 0, '{"UK 6":0,"UK 7":0,"UK 8":0,"UK 9":0,"UK 10":0}'::jsonb, '["/images/shoes/espresso-court.png"]'::jsonb, '[{"size":"UK 6","footLength":"25 cm"},{"size":"UK 7","footLength":"26 cm"},{"size":"UK 8","footLength":"27 cm"},{"size":"UK 9","footLength":"28 cm"},{"size":"UK 10","footLength":"29 cm"}]'::jsonb, false),
('midnight-court', 'Midnight Court', 'Everyday', 'Navy / White', 6290, '/images/shoes/midnight-court.png', 'New arrival', 'Midnight Court brings navy / white tones to your everyday rotation. A versatile silhouette made to pair with your favourite casual looks.', '["Lace-up silhouette","See size guide before ordering","Colour may vary slightly by screen"]'::jsonb, 0, '{"UK 6":0,"UK 7":0,"UK 8":0,"UK 9":0,"UK 10":0}'::jsonb, '["/images/shoes/midnight-court.png"]'::jsonb, '[{"size":"UK 6","footLength":"25 cm"},{"size":"UK 7","footLength":"26 cm"},{"size":"UK 8","footLength":"27 cm"},{"size":"UK 9","footLength":"28 cm"},{"size":"UK 10","footLength":"29 cm"}]'::jsonb, false),
('clay-retro', 'Clay Retro', 'Everyday', 'Terracotta / Cream', 6590, '/images/shoes/clay-retro.png', 'New arrival', 'Clay Retro brings terracotta / cream tones to your everyday rotation. A versatile silhouette made to pair with your favourite casual looks.', '["Lace-up silhouette","See size guide before ordering","Colour may vary slightly by screen"]'::jsonb, 0, '{"UK 6":0,"UK 7":0,"UK 8":0,"UK 9":0,"UK 10":0}'::jsonb, '["/images/shoes/clay-retro.png"]'::jsonb, '[{"size":"UK 6","footLength":"25 cm"},{"size":"UK 7","footLength":"26 cm"},{"size":"UK 8","footLength":"27 cm"},{"size":"UK 9","footLength":"28 cm"},{"size":"UK 10","footLength":"29 cm"}]'::jsonb, false),
('olive-trail', 'Olive Trail', 'Runners', 'Olive / Charcoal', 7490, '/images/shoes/olive-trail.png', 'New arrival', 'Olive Trail brings olive / charcoal tones to your everyday rotation. A versatile silhouette made to pair with your favourite casual looks.', '["Lace-up silhouette","See size guide before ordering","Colour may vary slightly by screen"]'::jsonb, 0, '{"UK 6":0,"UK 7":0,"UK 8":0,"UK 9":0,"UK 10":0}'::jsonb, '["/images/shoes/olive-trail.png"]'::jsonb, '[{"size":"UK 6","footLength":"25 cm"},{"size":"UK 7","footLength":"26 cm"},{"size":"UK 8","footLength":"27 cm"},{"size":"UK 9","footLength":"28 cm"},{"size":"UK 10","footLength":"29 cm"}]'::jsonb, false),
('onyx-knit', 'Onyx Knit', 'Runners', 'Black / Graphite', 6990, '/images/shoes/onyx-knit.png', 'New arrival', 'Onyx Knit brings black / graphite tones to your everyday rotation. A versatile silhouette made to pair with your favourite casual looks.', '["Lace-up silhouette","See size guide before ordering","Colour may vary slightly by screen"]'::jsonb, 0, '{"UK 6":0,"UK 7":0,"UK 8":0,"UK 9":0,"UK 10":0}'::jsonb, '["/images/shoes/onyx-knit.png"]'::jsonb, '[{"size":"UK 6","footLength":"25 cm"},{"size":"UK 7","footLength":"26 cm"},{"size":"UK 8","footLength":"27 cm"},{"size":"UK 9","footLength":"28 cm"},{"size":"UK 10","footLength":"29 cm"}]'::jsonb, false),
('ivory-platform', 'Ivory Platform', 'Everyday', 'Ivory / Beige', 6790, '/images/shoes/ivory-platform.png', 'New arrival', 'Ivory Platform brings ivory / beige tones to your everyday rotation. A versatile silhouette made to pair with your favourite casual looks.', '["Lace-up silhouette","See size guide before ordering","Colour may vary slightly by screen"]'::jsonb, 0, '{"UK 6":0,"UK 7":0,"UK 8":0,"UK 9":0,"UK 10":0}'::jsonb, '["/images/shoes/ivory-platform.png"]'::jsonb, '[{"size":"UK 6","footLength":"25 cm"},{"size":"UK 7","footLength":"26 cm"},{"size":"UK 8","footLength":"27 cm"},{"size":"UK 9","footLength":"28 cm"},{"size":"UK 10","footLength":"29 cm"}]'::jsonb, false)
on conflict (slug) do nothing;
commit;

